[package]
name = "kurt"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kurt"
path = "bin/main.rs"

[workspace]

[features]

[dependencies]
runtime = { path = "./src/runtime" }

[dependencies.clap]
version = "2.33"
features = [ "suggestions", "color", "wrap_help" ]