[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[features]
trace = []
gc_trace = []

[dependencies]
compiler = { path = "../compiler" }

[dev-dependencies]
syntax = { path = "../syntax" }
