[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[features]
trace = []
gc_trace = []

[dependencies]
diagnostic = { path = "../diagnostic" }
compiler = { path = "../compiler" }
common = { path = "../common" }
