[package]
name = "syntax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diagnostic = { path = "../diagnostic" }

# external
unicode_categories = "0.1"
unicode-xid = "0.2"
